# Generated by Django 5.0.2 on 2024-02-27 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("userID", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="PortfolioHistory",
            fields=[
                (
                    "port_history_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("date", models.DateTimeField()),
                ("portfolio_sum", models.FloatField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend_app.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Account_Stock",
            fields=[
                ("stock_order_id", models.AutoField(primary_key=True, serialize=False)),
                ("stock_symbol", models.CharField(max_length=10)),
                ("shares", models.FloatField()),
                ("average_price", models.FloatField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend_app.user",
                    ),
                ),
            ],
        ),
    ]
