# Generated by Django 4.2.10 on 2024-03-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_user_portfoliohistory_account_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(max_length=10)),
                ('time', models.IntegerField()),
                ('increase', models.BooleanField()),
                ('percent', models.IntegerField()),
                ('indicator', models.CharField(max_length=100)),
                ('increase_accuracy', models.FloatField()),
                ('percent_accuracy', models.FloatField()),
            ],
        ),
    ]
