# Generated by Django 5.0.2 on 2024-03-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend_app", "0003_stockprediction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockprediction",
            name="percent",
        ),
        migrations.AddField(
            model_name="stockprediction",
            name="high_percent",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stockprediction",
            name="low_percent",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
