# Generated by Django 5.0.2 on 2024-04-24 20:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend_app", "0004_remove_stockprediction_percent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockprediction",
            name="last_update",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stockprediction",
            name="peak",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
