# Generated by Django 5.0.2 on 2024-04-25 00:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend_app", "0005_stockprediction_last_update_stockprediction_peak"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stockprediction",
            old_name="peak",
            new_name="peak_high",
        ),
        migrations.AddField(
            model_name="stockprediction",
            name="peak_min",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="stockprediction",
            name="last_update",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
